### PR TITLE
chore(CI): Report coverage as a PR comment

### PR DESCRIPTION
**Pull request by rouk1**
A bot will now push(and edit) a single comment with coverage information.
Screenshot 2024-11-22 at 11 51 51

To achieve that this PR:
- uses a market place action to generate the comment
- to optimize action's duration coverage as been disable in the matrixed testing step
- to optimize action's and as frontend serving test was not pertinent it has been removed
- coverage is only run once in another task (linux | python 3.12)
- frontend artifact related stuff have been removed

### CODE REVIEW

**Comment by augustebaum** [comment]
Remind me, why does the coverage report include the `tests` directory? I also have it when I run locally

**Comment by rouk1** [comment]
> Remind me, why does the coverage report include the `tests` directory? I also have it when I run locally

You write this makes no sense. Hence I've added the tests folder to the omit rule of coverage.

**Review by augustebaum — APPROVED** [review]
Looks good to me!

**Comment by thomass-dev** [comment]
Please don't merge, my review is not finished.

**Review by thomass-dev — APPROVED** [review]
Strong work, thanks.

**Pull request merged**
