### PR TITLE
docs: Add cross_validate path

### PR DESCRIPTION
**Pull request by adrinjalali**
To make it clear that it's not the one from scikit-learn.

### CODE REVIEW

**Review by sylvaincom — APPROVED** [review]
LGTM, thanks

**Comment by sylvaincom** [comment]
What about the 3rd example on cross-validation?

**Comment by adrinjalali** [comment]
> What about the 3rd example on cross-validation?

I haven't gotten there yet.

**Comment by rouk1** [comment]
Sorry I updated the branch people told me that this is not nice.

**Comment by rouk1** [comment]
Edit PR title to please the CI.

**Review by rouk1 — APPROVED** [review]

**Pull request merged**
