### PR TITLE
docs: Remove warnings raised by sphinx

### PR DESCRIPTION
**Pull request by glemaitre**
This PR removes warnings when building the documentation with sphinx.

### CODE REVIEW

**Comment by glemaitre** [comment]
It looks like a similar issue than in #951 related with coverage. It looks like there is something fishy with the workflow there.

**Review by augustebaum — APPROVED** [review]
Great, thanks!

**Comment by thomass-dev** [comment]
@glemaitre can you please merge the conflict by rebasing to main?

**Comment by glemaitre** [comment]
Should be fine now.

**Review by thomass-dev — APPROVED** [review]

**Comment by sylvaincom** [comment]
Many thanks!

**Pull request merged**
