### PR TITLE
docs: Use Git LFS to store images

### PR DESCRIPTION
**Pull request by thomass-dev**
You can now put images in `sphinx/_static/images/` to store heavy documentation files directly in the repository.
You must have installed `git-lfs` when cloning the repository (your prompt will emit a warning otherwise).

image

### CODE REVIEW

**Comment by thomass-dev** [comment]
@sylvaincom please can you check that the documentation is correct on your laptop, by cloning the branch and building the documentation? (it works on mine).

**Comment by sylvaincom** [comment]
It works, thanks!

**Review by sylvaincom — APPROVED** [review]
It works, thanks!

**Comment by thomass-dev** [comment]
WIP: try to address https://github.com/probabl-ai/skore/issues/873

**Comment by sylvaincom** [comment]
I got this in the getting started example?

Capture d’écran 2024-12-06 à 14 28 39

**Comment by thomass-dev** [comment]
As i said here, the links are not yet accessible because they refer to main https://github.com/probabl-ai/skore/pull/870#issuecomment-2522651110.

**Review by rouk1 — APPROVED** [review]
Nice, will probably move frontend assets to lfs in a future PR.

**Comment by thomass-dev** [comment]
@sylvaincom i can see a bug in the CI, i will open a new PR.

**Pull request merged**
