### PR TITLE
feat(UI): Dismiss non-error toasts automatically after 20 seconds

### PR DESCRIPTION
**Pull request by rouk1**
New options have been added to the `addToast` function:

 - dismissible : Whether the toast can be dismissed by the user. Default is true.
 - duration : The duration in seconds for which the toast should be displayed. Default is Infinity.

Also, the toast area was moved to the top of the app.

UI preview (before the toast area was moved):

https://github.com/user-attachments/assets/3b2a0095-85f8-4de4-b038-8797df893d52

### CODE REVIEW

**Review by augustebaum — CHANGES_REQUESTED** [review]
Doesn't work in dark mode:

https://github.com/user-attachments/assets/d66b8c0d-8acc-46cb-8401-040fa4ff2aae

**Comment by rouk1** [comment]
> Doesn't work in dark mode: https://github.com/user-attachments/assets/86c769ac-58ef-4cfc-a314-e1c4465947a3

Toast now use same skin in dark & light mode as requested in #525. Toast area is now on center top of the user's viewport.

**Comment by augustebaum** [comment]
Still doesn't work in dark mode

https://github.com/user-attachments/assets/89043a81-75f0-4079-b797-11c95e95f02e

But now:
- It also doesn't work in light mode (I can't see the feedback, like in dark mode)
- The buttons on the top bar (to collapse the side bar and to add a view) are covered by the ToastArea, so they don't work anymore
- The buttons to add items to the view also don't work -- not sure if this is from this PR.

I think the safest would be to remove the moving of the toast area from this PR, and put it in a new one. Meanwhile, I'll set this back to draft until @rouk1 comes back from vacation.

**Comment by rouk1** [comment]
> Still doesn't work in dark mode
> 2024-10-23T11_18_25_screen_record.mp4
> 
> But now:
> 
>     * It also doesn't work in light mode (I can't see the feedback, like in dark mode)
> 
>     * The buttons on the top bar (to collapse the side bar and to add a view) are covered by the ToastArea, so they don't work anymore
> 
>     * The buttons to add items to the view also don't work -- not sure if this is from this PR.
> 
> 
> I think the safest would be to remove the moving of the toast area from this PR, and put it in a new one. Meanwhile, I'll set this back to draft until @rouk1 comes back from vacation.

The toast area does not intercept clicks anymore. Only the dismiss button will.
Can we check together why you do not see the countdown feedback ?

**Comment by rouk1** [comment]
@augustebaum as discussed your version of firefox is outdated and does not support css @property rules.
https://caniuse.com/?search=%40property

**Comment by augustebaum** [comment]
Yep thanks for going over it, all the issues seem to be solved. Eventually we might implement some kind of graceful degradation.

**Review by augustebaum — APPROVED** [review]

**Pull request merged**
